data:
  source-name: wav2vec_large_data_sum  # if you process data with a preprocessor, this name will be taken as the data output directory.
  dataset:
    name: RAVDESS
    batch-size: 32
    train-size: 0.7
    test-size: 0.1
    desired-sampling-rate: 16000
    prefetch: 2
    desired-length: null
    padding-value: 0.0
    shuffle-seed: null
model:
  wav2vec2:
    name: Wav2vecClassifier
    pretrained-model: facebook/wav2vec2-base-960h
    save-dir: ../../results/saved_models/ravdess_mlp_clf
    aggregation: mean
    mode: training # {training, testing}
    train-epochs: 2
  gemaps-mfcc:
    plot-dir: ../../results/plots
    mfcc:
      number-coefficients: 25
    gmaps:





